services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config", "/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
