receivers:
  otlp:
    protocols:
      grpc:
        # OTeL receiver endpoint (grpc)
        endpoint: 127.0.0.1:4317
      http:
        # OTeL receiver endpoint (http)
        endpoint: 127.0.0.1:4318
  kafkametrics:
    brokers:
      # Kafka brokers endpoints
      - 127.0.0.1:9092
      - 127.0.0.1:9093
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers
  jmx:
    # configure the path where you installed opentelemetry-jmx-metrics receiver
    jar_path: ${PWD}/opentelemetry-jmx-metrics.jar
    endpoint: service:jmx:rmi:///jndi/rmi://127.0.0.1:2020/jmxrmi
    target_system: kafka
    collection_interval: 10s
    log_level: info
  jmx/2:
    # configure the path where you installed opentelemetry-jmx-metrics receiver
    jar_path: ${PWD}/opentelemetry-jmx-metrics.jar
    endpoint: service:jmx:rmi:///jndi/rmi://127.0.0.1:2021/jmxrmi
    target_system: kafka
    collection_interval: 10s

exporters:
  otlp:
    # configure the grpc endpoint for signoz otel collector
    endpoint: 127.0.0.1:51957
    tls:
      insecure: true
  otlphttp:
    # configure the http endpoint for signoz otel collector
    endpoint: 127.0.0.1:51958
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp, jmx, jmx/2, kafkametrics]
      exporters: [otlp, debug]
